dist: xenial

language: node_js
node_js:
  - "12.16.3"

install:
  - npm install

script:
  - ng lint
  - ng test --watch=false --browsers=ChromeHeadless
  - ng build --prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/formio-editor-demo
  on:
    branch: master
